COSCUP/COSCUP-Volunteer

celery_task/task_mail_sys.py, celery_task/task_service_sync.py, models/index.py, models/teamdb.py, module/mattermost_bot.py, module/project.py, templates/project_edit.html, templates/team.html, templates/team_plan_edit.html, view/project.py, view/team.py
先增人員加入到「志工服務系統」發出邀請使用 Mattermost。
加入到 Team 發出要請到 Project 的主要 Channel（如：`coscup-2020`）的流程還在找適當的切入點。
=> Mattermost invite

models/index.py, models/teamdb.py, templates/team.html, templates/team_plan_edit.html, view/team.py
新增「時程規劃」工具，與可以顯示其他組的事件一起比較時間安排。
用到 Google Chart: `Calendar`, `Timelines`
=> Plan timeline

celery_task/task_service_sync.py, module/team.py, templates/project_edit_create_team.html, view/project.py
=> Add team disabled switch

celery_task/celery.py, celery_task/task_ipinfo.py, main.py, models/usessiondb.py, module/gsuite.py, module/usession.py, restart_app.sh, templates/setting.html, templates/setting_security.html
=> Login session

module/waitlist.py, templates/base.html, templates/setting.html, templates/setting_waitting.html, view/setting.py
=> Add waitting status for user

models/formdb.py, module/form.py, module/project.py, templates/form_traffic_fee.html, templates/project_edit.html, templates/project_edit_base.html, templates/project_form_traffic_mapping.html, view/project.py, view/team.py
=> Traffic mapping

module/form.py, templates/form.html, templates/form_clothes.html, templates/project_form.html, templates/team.html, view/project.py, view/team.py
=> Clothes size

module/form.py, module/users.py, templates/form_accommodation.html, templates/project_edit_base.html, templates/project_form_accommodation.html, view/project.py, view/team.py
這個是建立住宿可以線上交換同房的功能。後台還需要一個可以匯出住宿名單的功能，給商旅使用。
=> Accommodation

module/sender.py
感謝 @daluntw 回報 jinja2 Template Injection SSTI 問題。
=> Fixed jinja2 Template Injection SSTI

module/sender.py
change all Environment to SandboxedEnvironment to prevent SSTI Injection
=> fix SSTI security issue

templates/tasks_project.html
Prevent xss attack in v-html
Ref: https://vuejs.org/v2/guide/security.html
=> Change <v-html> to <pre>

module/dietary_habit.py, module/users.py, templates/project_dietary_habit.html, templates/project_edit_base.html, templates/setting_profile_real.html, view/project.py, view/setting.py
新增 **飲食習慣** 調查。**個人真實資料**改用 vuejs 取資料。
=> Dietary habit

main.py, module/users.py
新增使用者停權欄位。 
- `property.suspend` = `True` 停權。
=> User suspend

models/index.py, models/senderdb.py, models/teamdb.py, module/sender.py, module/team.py, templates/sender_campaign_receiver.html, templates/sender_campaign_schedule.html, templates/team_edit_user.html, templates/team_members.html, view/sender.py, view/team.py
實作組員可以設定小組分類（tags），在寄送信件也可以使用。
=> Team member tags

Dockerfile-app, Dockerfile-base, celery_task/celery.py, celery_task/task_expense.py, celery_task/task_service_sync.py, main.py, models/budgetdb.py, models/expensedb.py, models/index.py, module/budget.py, module/expense.py, module/team.py, module/users.py, templates/base.html, templates/budget.html, templates/expense.html, templates/expense_lists.html, templates/expense_menu.html, templates/expense_my.html, templates/form_volunteer_certificate.html, templates/tasks_project.html, templates/team.html, view/budget.py, view/expense.py, view/sender.py, view/tasks.py, view/team.py
預算經費申請系統
詳細功能說明可以參考 https://github.com/COSCUP/COSCUP-Volunteer/wiki/%E9%A0%90%E7%AE%97%E3%80%81%E7%B6%93%E8%B2%BB%E7%94%B3%E8%AB%8B%E6%B5%81%E7%A8%8B
備註：開發時間剛好歷經整個三級警戒。
=> Budget 預算經費申請系統

Dockerfile-app, celery_task/task_service_sync.py, main.py, models/users_db.py, module/skill.py, module/users.py, requirements.txt, templates/recruit_list.html, templates/setting_profile.html, templates/team.html, templates/team_edit.html, view/project.py, view/recruit.py, view/setting.py, view/user.py
Add skill page at user's profile in settings. This feature may help us to find volunteer in user's skills.
=> Skill page

Dockerfile-app, build-base.sh, docker-compose.yml, models/expensedb.py, nginx/Dockerfile, nginx/logrotate/nginx, nginx/nginx.conf, nginx/sites/volunteer_dev.conf, setting_sample.py
Using docker-compose for contributor to develop, this PR still not resolve the Google SSO client token.
=> Add docker-compose

.github/workflows/pytest.yml, models/base.py, models/oauth_db.py, models/users_db.py, module/users.py, pyproject.toml, requirements.txt, setting_sample.py, tests/test_module_users.py
Add pytest for starting to write the testing cases.
=> Add pytest

.github/workflows/build_image.yml
Add github action for building docker images of base, app.
=> Add action for building Docker base and app

module/budget.py
=> Extend the permission for the fin's members

module/budget.py, view/team.py
=> Add enable argument for query budget

.github/workflows/build_image.yml, .github/workflows/docker-compose.yml, .github/workflows/pytest.yml, Dockerfile-app, Dockerfile-app-dev, Dockerfile-base, README.md, build-base.sh, docker-compose.yml, poetry.lock, pyproject.toml, start_app.sh, start_celery.sh
改用 Poetry 取代 pip 作為套件管理。感謝 @pan93412 的協助！
#40 #41
=> Replace pip with Poetry

module/expense.py, templates/expense_lists.html, view/team.py
新增已申請單據的總額與剩餘預算試算。
目前只能每筆申請單的資訊很獨立，無法針對已申請過的整合資訊。
Issue Number: Resolves #64 
- 條列顯示已申請的單據項目。
- 金額試算區，此次申請金額、已申請金額、預算差額。
無
=> Show the sent invoices total

.github/workflows/build_image.yml, Dockerfile-app, Dockerfile-app-dev, Dockerfile-base, build-base.sh, docker-compose.yml, poetry.lock
Upgrade
- alpine 3.15.4
- jemalloc 5.3.0
- update python dependencies
=> Update alpine, jemalloc, python dependency

docker-compose.yml, start_memcached.sh, start_mongo.sh, start_rabbitmq.sh
Upgrade mongodb, memcached, rabbitmq in prod
- `memcached:1.6.15-alpine`
- `mongo:5.0.8-focal`
- `rabbitmq:3.8.30-management-alpine`
=> Upgrade mongodb, memcached, rabbitmq in prod

Dockerfile-app, models/budgetdb.py, models/expensedb.py, module/budget.py, module/expense.py, templates/budget.html, templates/budget_batch.html, templates/expense.html, templates/expense_lists.html, templates/expense_my.html, templates/form_accommodation.html, view/budget.py, view/team.py
- 支援可大量匯入預算項目（[匯入格式](https://github.com/COSCUP/COSCUP-Volunteer/wiki/%E9%A0%90%E7%AE%97%E8%A1%A8%EF%BC%88budget%EF%BC%89#%E5%A4%A7%E9%87%8F%E5%8C%AF%E5%85%A5%E9%A0%90%E7%AE%97%E9%A0%85%E7%9B%AE%E6%A0%BC%E5%BC%8F%E8%A1%A8)）
- 修正使用較短的唯一編號，新增欄位 `code` 來顯示。
無大量上傳預算表的功能，需要一筆一筆建立。`唯一編號`亂數太過於長不容易使用。
Issue Number: resolved #63 #68
- 提供能大量上傳已審核過的預算項目。
- `唯一編號`使用 4 碼的的方式呈現。
文件： [大量匯入預算項目格式表](https://github.com/COSCUP/COSCUP-Volunteer/wiki/%E9%A0%90%E7%AE%97%E8%A1%A8%EF%BC%88budget%EF%BC%89#%E5%A4%A7%E9%87%8F%E5%8C%AF%E5%85%A5%E9%A0%90%E7%AE%97%E9%A0%85%E7%9B%AE%E6%A0%BC%E5%BC%8F%E8%A1%A8)
=> batch import budget 大量匯入預算項目

celery_task/task_ipinfo.py, module/awsses.py, module/gitlab_api.py, module/gsuite.py, module/ipinfo.py, module/telegram_bot.py
修正為 type hint 與不複寫 `requests.session` funs.
現在的寫法會造成 pylint 提示錯誤。
- type hint
- fit pylint policy
N/A
=> Refactor the third party API in type hint

view/api.py
Order members in /api/members
order by user created at.
Issue Number: #78 
- By manual order in admin page.
None
=> Change return chiefs data in order

module/project.py, templates/form_parking_card.html, templates/project_edit.html, view/project.py, view/team.py
Change the parking card into options data not hard code.
Hard code the date options.
Issue Number: #77 
- Add new field for parking card data in project field.
None
=> 77 parking card

templates/form_clothes.html, view/project.py, view/team.py
Signed-off-by: Toomore Chiang <toomore0929@gmail.com>
Add `How to get the clothes` options in form.
In 2021, we host the COSCUP online, our volunteers have no memorial cloths in that year.
This year, COSCUP will be in-person activity, we need investigate the size and how to get for 2021's volunteers.
Issue Number: #76 
Add options for volunteers to select the best way to get the clothes.
N/A
=> Add how to get the clothes in form

README.md, docs_dev/docs/dev/beginners.md
- Add `libmemcached` package installation approach for other common Linux-based distributions.
=> Add libmemcached for other Linux distributions

templates/budget.html, view/budget.py
Signed-off-by: Toomore Chiang <toomore0929@gmail.com>
Fixed the duplicate bid created by manually.
No any alert or notice for creator to know the budget number is duplicate.
Issue Number: #90 
- If in duplicate, the field of budget will turn to red. 
N/A
=> Fixed the duplicate bid created by manually #90

models/expensedb.py, module/expense.py, templates/expense.html, templates/expense_my.html, templates/form_accommodation.html, view/expense.py, view/team.py
Fixed #92 #93 #94 #95
Update expense status, and update the submitted expense's content, total.
The submitted expense can not update.
Issue Number: #92 #93 #94 #95
- Update submitted expense's status.
- Update submitted expense's content.
- Remove submitted expense.
N/A
=> 92 update my expense

.gitignore, api/main.py, docker-compose.yml, docs_dev/entrypoint.sh, main.py, nginx/sites/volunteer_dev.conf
更改開發階段時建立 container 的方式與相關設定，並支援 hot reload
Issue Number: #125
- 使用 bind mount 將檔案放入 container
- 使用 flask 內建的 WSGI server 代替 uwsgi 並加入 `--debug` 參數，使 python 程式碼變更後自動重跑
- uvicorn 加入 `--debug`  參數，使 `/api` 內的程式碼變更後自動重跑
- 開啟 `app.config['TEMPLATES_AUTO_RELOAD']`，使 templates 變更後重整瀏覽器可以下載到新的程式碼
**額外**
- 修改 docs site 後可直接執行 `docker compose run docs` 建立文件
目前 main.py 與 setting.py 更改後 server 無法自動重跑，測試後發現如果 mount 單一檔案到 container 時才會發生此現象
=> Support hot reload #125

module/expense.py, view/expense.py
修改匯出報表的格式
Issue Number: #123 
- 將指定欄位改為中文
- 匯出 `可使用` 的申請單
- 除原指定欄位以外，另外新增 `預算貨幣` 與 `單據貨幣` 兩個欄位
`會計科目` 需等待 #121 完成，待完成後再補上
=> Expense csv format

module/dispense.py, static/ExpenseTable.js, static/InvoiceList.js, templates/expense.html
Fix POST /dispense 500 error
1. Use python way to handle non-existed key
2. Wrap long invoice list properly #143 
> ![螢幕快照 2023-05-21 22-51-56](https://github.com/COSCUP/COSCUP-Volunteer/assets/271157/50f11deb-3f29-4434-8628-5da9c77aa509)
=> Expense page related bug fix

static/ExpenseStatusLabel.js
#112 , apply different color first.
1. 先至少讓每個狀態有各自的顏色
> ![圖片](https://github.com/COSCUP/COSCUP-Volunteer/assets/271157/63e63db8-480c-46ff-9362-55d4f1486537)
2. 變色力異常的部份，先以不同的 icon 區別，有空時，再回來加強
=> feat: set different color for each expense state

module/dispense.py, templates/expense.html, view/dispense.py
新增匯出出款單功能
Issue Number: #124 
- 在 `/expense` 頁面新增 `匯出出款單(CSV)` 的按鈕
- 除原本申請單欄位外，增加以下兩個欄位
- 出款日期
- 出款總金額
- 按照出款日期以及建立日期排序，由小到大
- 匯出後如有時間日期格式錯亂的問題，需手動調整 Excel 的格式設定
**範例圖片：**
=> Export dispense csv file

main.py, models/trackdb.py, module/track.py, templates/base.html, templates/schedule.html, templates/schedule_talks.html, templates/tasks_project.html, view/schedule.py
- Talks can't support save or bookmark.
- Add talks to favorite
- Share the favorite talks
Add and share favorite talks need to login.
=> Forms with My favorite talks

.github/workflows/build_image.yml, .github/workflows/docker-compose.yml, Dockerfile-app, Dockerfile-app-dev, Dockerfile-base, Dockerfile-base-dev, build-base.sh, docker-compose.yml, docs_dev/docs/dev/build-base-image.md, docs_dev/docs/dev/build-base-image.zh-TW.md, nginx/Dockerfile, poetry.lock, pyproject.toml, start_memcached.sh, start_mongo.sh, start_rabbitmq.sh
N/A
docker images:
- python:3.11.7-alpine3.19
- memcached:1.6.22-alpine
- rabbitmq:3.11.27-management-alpine
- mongo:6.0.12-jammy
- nginx:1.25.3-alpine
=> Pre 231223

templates/team_join_to.html
應完成事項才能申請的提醒 
修正加入前的警示，如尚未完成新手任務是無法開始申請。
請先至上方 <strong>「請先完成以下事項」</strong> 紅色區域，依指示逐條完成代辦事項，即可開啟申請功能。
Warning before initiation: If the novice tasks are not completed, you cannot start the application process. Please go to the red area above titled <strong>'Please Complete the Following Tasks'</strong> and follow the instructions to complete each item on the to-do list. Once these are done, the application function will be activated.
-  team_join_to.html 增加 {% if messages %} 的判斷句，來改變下方顯示的警告，以利新的使用者。
=> Reminder those tasks must be completed before applying as Team members.

docs_dev/docs/about_coscup/team_member_handbook.zh-TW.md
Issue Number: [Telegram](https://t.me/coscupchat/37242)
I correct the URL scheme of `coscup.org`.
=> docs: Typo in URL scheme: "https:/coscup.org/"

.github/workflows/build_docs.yml
- Node.js 16 actions are deprecated. Update `actions/cache@v3` to `actions/cache@v4`
N/A
=> chore: update actions/cache to v4

.github/workflows/codeql-analysis.yml
- Update codeql-actions@v3 to codeql-actions@v4
N/A
=> chore: update codeql-actions to v3

templates/expense_lists.html
- fix https://github.com/COSCUP/COSCUP-Volunteer/issues/198#issue-2156101754
=> fix: https://github.com/COSCUP/COSCUP-Volunteer/issues/198#issue-2156101754

templates/setting_profile.html
- Add format to the placeholder in the intro.
- Resolve https://github.com/COSCUP/COSCUP-Volunteer/issues/195.
Add format to the placeholder in the intro.
N/A
=> fix: https://github.com/COSCUP/COSCUP-Volunteer/issues/195

module/dispense.py, module/expense.py, view/team.py
抓取「我的申請單」時邏輯出錯
- Issue Number: #211 
修正邏輯
=> Expense bug#211

main.py, static/ExpenseEditor.js, static/ExpenseInvoiceTotalCard.js, templates/expense.html
Issue Number: #212 
- 在 ExpenseEditor 新增以下兩筆資料
- 已申請合計：採該筆預算底下所有請款單單據（包含正在編輯審核中的請款單）的總和
- 預算餘額計算：預算總金額 - 已申請合計
=> 在「管理預算申請列表」裡面新增預算餘額資訊

module/dispense.py
當使用者查詢 **我的申請單** 時，可看到已被刪除的出款單出現在 **出款中、已出款、已完成** 區塊
- Issue Number: [#211 ](https://github.com/COSCUP/COSCUP-Volunteer/issues/211#issuecomment-2119332557)
- 後端回傳 **我的申請單** 時，不包括已刪除的出款單
=> Exclude disabled dispenses when retrieving my expense

Dockerfile-app, Dockerfile-app-dev
Production 環境內缺少部分 static file，導致請求該檔案時回傳 404
- Issue Number: https://github.com/COSCUP/COSCUP-Volunteer/issues/212#issuecomment-2208484411
- 在 Production Image 中新增以下檔案
- static/ExpenseInvoiceTotalCard.js
=> Add a static file to production image

docs_dev/docs/about_coscup/calendar.md
Remove misspelled word, slightly improve the wording.
`Driect` is a typo.
- Removed the typo `Driect` and improves the wording slightly.
-
-
=> Fix typo in calendar.md

templates/base.html, templates/expense_lists.html, templates/index.html
Update links in template for COSCUP 2025.
- Update 2025 expense form / rules
- Update 2025 group links
- Update 2025 task links
Traffic expense and program schedule are in 2024 now. I will go back to update them.
=> Update 2025 links for base.html, expense_lists.html, and index.html

docs_dev/docs/about_coscup/attendee_services/index.md, docs_dev/docs/about_coscup/attendee_services/index.zh-TW.md, docs_dev/docs/global_engagement/hello_world.md, docs_dev/mkdocs.yml
Remove events not in 2025
-
-
-
=> Remove 2024 events and modify some information from 2024 to 2025
